# Generated by Django 4.1 on 2024-04-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=128),
        ),
    ]
